# Generated by Django 5.2.10 on 2026-05-09 21:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=260)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('thematic_track', models.CharField(blank=True, max_length=120)),
                ('narrative', models.TextField(blank=True)),
                ('agendas', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, upload_to='event_covers/')),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('venue_descriptor', models.CharField(blank=True, max_length=255)),
                ('ticketing_enabled', models.BooleanField(default=False)),
                ('ticketing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ticketing_currency', models.CharField(default='KES', max_length=8)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('public_qr_seed', models.CharField(blank=True, max_length=120)),
                ('reminders_email', models.BooleanField(default=True)),
                ('reminders_sms', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('volunteering_open', models.BooleanField(default=False)),
                ('organizer_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to='organizations.communitygroup')),
                ('stewardship_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='event_archive/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('attribution', models.CharField(blank=True, max_length=160)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='events.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventTicket',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('redeemed', 'Redeemed')], default='issued', max_length=32)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.event')),
                ('holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('reserved', 'Confirmed'), ('waitlisted', 'Waitlisted'), ('declined', 'Declined')], default='reserved', max_length=32)),
                ('companions', models.PositiveSmallIntegerField(default=0)),
                ('dietary_notes', models.CharField(blank=True, max_length=160)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp_history', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp_entries', to='events.event')),
            ],
            options={
                'unique_together': {('event', 'attendee')},
            },
        ),
    ]
