# Generated by Django 5.2.10 on 2026-05-09 21:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanLane',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=96, unique=True)),
                ('caption', models.CharField(max_length=160)),
                ('color_token', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_code', models.CharField(blank=True, max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('problem_statement', models.TextField(blank=True)),
                ('anticipated_outcomes', models.TextField(blank=True)),
                ('budget_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('funding_secured', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('timeline_start', models.DateField(blank=True, null=True)),
                ('timeline_end', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('wards_served', models.CharField(blank=True, max_length=255)),
                ('sdg_goals', models.JSONField(blank=True, default=list)),
                ('beneficiaries_count', models.PositiveIntegerField(default=0)),
                ('intervention_tags', models.CharField(blank=True, max_length=400)),
                ('transparency_summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=32)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0)),
                ('cover_image', models.ImageField(blank=True, upload_to='project_media/')),
                ('spotlight_video_url', models.URLField(blank=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='organizations.communitygroup')),
                ('steward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steward_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KanbanMembership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.kanbanlane')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_card', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('narrative', models.TextField(blank=True)),
                ('baseline_date', models.DateField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectStakeholder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_name', models.CharField(blank=True, max_length=255)),
                ('role_label', models.CharField(max_length=160)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder_links', to='projects.project')),
                ('stakeholder_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stakeholding_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['project'], name='projects_pr_project_8eaf5b_idx')],
            },
        ),
    ]
