# Generated by Django 5.2.10 on 2026-05-09 21:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=260, unique=True)),
                ('tier', models.CharField(blank=True, max_length=64)),
                ('logo', models.ImageField(blank=True, upload_to='sponsors/')),
                ('headline', models.TextField(blank=True)),
                ('thematic_alignment', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('liaison_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_sponsors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=64)),
                ('donor_display_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tribute_message', models.TextField(blank=True)),
                ('earmark_category', models.CharField(blank=True, max_length=120)),
                ('currency', models.CharField(default='KES', max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('anonymous', models.BooleanField(default=False)),
                ('channel', models.CharField(choices=[('card', 'Stripe / Card'), ('paypal', 'PayPal'), ('mpesa', 'M-Pesa'), ('bank', 'Bank / Cheque')], default='card', max_length=32)),
                ('paypal_order_id', models.CharField(blank=True, max_length=96)),
                ('stripe_session_id', models.CharField(blank=True, max_length=128)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=128)),
                ('mpesa_checkout_request_id', models.CharField(blank=True, max_length=128)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=64)),
                ('ledger_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Settled'), ('failed', 'Failed / Reversed')], default='pending', max_length=32)),
                ('disbursement_proof', models.FileField(blank=True, upload_to='donation_proofs/')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pledges_recorded', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations_allocated', to='projects.project')),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_donations', to='funding.sponsor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
