# Generated by Django 5.2.10 on 2026-05-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, editable=False, max_length=24, unique=True)),
                ('kind', models.CharField(choices=[('money', 'Financial contribution'), ('resources', 'In-kind resources (sports, farming, trees, etc.)'), ('message', 'Letter, proposal, or written inquiry')], db_index=True, max_length=32)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='KES', max_length=8)),
                ('payment_preference', models.CharField(blank=True, help_text='e.g. M-Pesa, bank, card, will follow up', max_length=64)),
                ('resource_category', models.CharField(blank=True, choices=[('sports', 'Sports & recreation'), ('farming', 'Farming & agriculture'), ('trees', 'Trees, seedlings & re-greening'), ('education', 'Education & literacy'), ('health', 'Health & sanitation'), ('water', 'Water & irrigation'), ('youth', 'Youth programmes'), ('women', 'Women’s empowerment'), ('general', 'General / mixed in-kind')], max_length=32)),
                ('resource_description', models.TextField(blank=True)),
                ('quantity_or_estimate', models.CharField(blank=True, max_length=255)),
                ('message_subject', models.CharField(blank=True, max_length=255)),
                ('message_body', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, upload_to='donor_intake_attachments/')),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('anonymous', models.BooleanField(default=False, help_text='If true, name is withheld from public honour rolls; KKEF may still contact you privately.')),
                ('email_to_team_sent_at', models.DateTimeField(blank=True, null=True)),
                ('staff_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
