# Generated by Django 5.2.10 on 2026-05-09 21:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=32)),
                ('slug', models.SlugField(blank=True, max_length=260)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('environment', 'Environment & Climate Action'), ('youth', 'Youth Empowerment'), ('agriculture', 'Agriculture & Food Systems'), ('fish_farming', 'Aquaculture / Fish Farming'), ('women', 'Women Empowerment'), ('cleanup', 'Community Clean-Up'), ('education', 'Education & Literacy'), ('water', 'Water Projects'), ('health', 'Community Health')], db_index=True, max_length=40)),
                ('synopsis', models.TextField()),
                ('rationale', models.TextField(blank=True)),
                ('implementation_plan', models.TextField(blank=True)),
                ('risk_register', models.TextField(blank=True)),
                ('projected_budget', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cofunding_commitments', models.TextField(blank=True)),
                ('beneficiaries_estimate', models.PositiveIntegerField(default=0)),
                ('sdg_tags', models.JSONField(blank=True, default=list)),
                ('template_key', models.CharField(blank=True, max_length=120)),
                ('ai_draft_hints', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Stakeholder Queue'), ('awaiting_approval', 'Awaiting Executive Approval'), ('approved', 'Approved'), ('rejected', 'Returned for Revision')], db_index=True, default='draft', max_length=48)),
                ('stakeholder_deadline_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_pdf', models.FileField(blank=True, upload_to='proposal_exports/')),
                ('authored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_proposals', to=settings.AUTH_USER_MODEL)),
                ('owning_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='organizations.communitygroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='proposal_documents/')),
                ('label', models.CharField(blank=True, max_length=160)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='proposals.proposal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProposalDigitalSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_label', models.CharField(max_length=120)),
                ('signature_blob', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='proposals.proposal')),
                ('signer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalReview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stakeholder_label', models.CharField(blank=True, max_length=160)),
                ('commentary', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('decision', models.CharField(choices=[('in_progress', 'Commentary'), ('endorsed', 'Endorsed'), ('flagged', 'Flagged Risks')], max_length=32)),
                ('digitally_signed_manifest', models.TextField(blank=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('confidentiality_level', models.CharField(blank=True, max_length=64)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='proposals.proposal')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_reviews_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
