# Generated by Django 5.2.10 on 2026-05-09 21:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('projects', '0001_initial'),
        ('proposals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=260, unique=True)),
                ('doc_type', models.CharField(choices=[('policy', 'Policy / Constitution'), ('financial', 'Financial Statement'), ('impact', 'Impact Evaluation'), ('proposal_draft', 'Proposal Working File'), ('memo', 'Memorandum'), ('other', 'Other')], default='other', max_length=40)),
                ('visibility', models.CharField(choices=[('public', 'Citizen Transparency'), ('partner', 'Partner Secure'), ('board', 'Executive / Board Only')], db_index=True, default='public', max_length=32)),
                ('file', models.FileField(upload_to='secure_registry/')),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('digest_sha256', models.CharField(blank=True, max_length=64)),
                ('version_label', models.CharField(default='v1', max_length=32)),
                ('confidentiality_note', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_cleared', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_registry', to='organizations.communitygroup')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivative_versions', to='documents.document')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_registry', to='projects.project')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_registry', to='proposals.proposal')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
