"""
Kiambu County administrative data for public forms (IEBC wards, ~60 wards in 12 constituencies).
Values are stable slugs; labels include constituency for duplicate names like "Township".
"""

# (value, label) — value stored in DB, label shown in dropdown
KIAMBU_WARD_CHOICES = (
    ("gituamba", "Gituamba — Gatundu North"),
    ("githobokoni", "Githobokoni — Gatundu North"),
    ("chania", "Chania — Gatundu North"),
    ("mangu", "Mang'u — Gatundu North"),
    ("kiamwangi", "Kiamwangi — Gatundu South"),
    ("kiganjo", "Kiganjo — Gatundu South"),
    ("ndarugo", "Ndarugo — Gatundu South"),
    ("ngenda", "Ngenda — Gatundu South"),
    ("murera", "Murera — Juja"),
    ("theta", "Theta — Juja"),
    ("witeithie", "Witeithie — Juja"),
    ("kalimoni", "Kalimoni — Juja"),
    ("juja", "Juja — Juja"),
    ("thika_township", "Township — Thika Town"),
    ("kamenu", "Kamenu — Thika Town"),
    ("hospital", "Hospital — Thika Town"),
    ("gatuanyaga", "Gatuanyaga — Thika Town"),
    ("ngoliba", "Ngoliba — Thika Town"),
    ("gitothua", "Gitothua — Ruiru"),
    ("biashara", "Biashara — Ruiru"),
    ("gatongora", "Gatongora — Ruiru"),
    ("kahawa_sukari", "Kahawa Sukari — Ruiru"),
    ("kahawa_wendani", "Kahawa Wendani — Ruiru"),
    ("kiuu", "Kiuu — Ruiru"),
    ("mwiki", "Mwiki — Ruiru"),
    ("mwihoko", "Mwihoko — Ruiru"),
    ("githunguri", "Githunguri — Githunguri"),
    ("githiga", "Githiga — Githunguri"),
    ("ikinu", "Ikinu — Githunguri"),
    ("ngewa", "Ngewa — Githunguri"),
    ("komothai", "Komothai — Githunguri"),
    ("tinganga", "Ting'ang'a — Kiambu"),
    ("ndumberi", "Ndumberi — Kiambu"),
    ("riabai", "Riabai — Kiambu"),
    ("kiambu_township", "Township — Kiambu"),
    ("cianda", "Cianda — Kiambaa"),
    ("karuri", "Karuri — Kiambaa"),
    ("ndenderu", "Ndenderu — Kiambaa"),
    ("muchatha", "Muchatha — Kiambaa"),
    ("kihara", "Kihara — Kiambaa"),
    ("gitaru", "Gitaru — Kabete"),
    ("muguga", "Muguga — Kabete"),
    ("nyadhuna", "Nyadhuna — Kabete"),
    ("kabete", "Kabete — Kabete"),
    ("uthiru", "Uthiru — Kabete"),
    ("karai", "Karai — Kikuyu"),
    ("nachu", "Nachu — Kikuyu"),
    ("sigona", "Sigona — Kikuyu"),
    ("kikuyu", "Kikuyu — Kikuyu"),
    ("kinoo", "Kinoo — Kikuyu"),
    ("bibirioni", "Bibirioni — Limuru"),
    ("limuru_central", "Limuru Central — Limuru"),
    ("ndeiya", "Ndeiya — Limuru"),
    ("limuru_east", "Limuru East — Limuru"),
    ("ngecha_tigoni", "Ngecha Tigoni — Limuru"),
    ("kinale", "Kinale — Lari"),
    ("kijabe", "Kijabe — Lari"),
    ("nyanduma", "Nyanduma — Lari"),
    ("kamburu", "Kamburu — Lari"),
    ("lari_kirenga", "Lari / Kirenga — Lari"),
)

GROUP_APPLICATION_TYPE_CHOICES = (
    ("cbo", "Community Based Organisation (CBO)"),
    ("self_help", "Self-Help Group"),
    ("savings", "Savings Group / Table Banking"),
    ("women", "Women Group / Women Enterprise"),
    ("youth", "Youth Group / Youth Forum"),
    ("sacco", "SACCO / Financial Cooperative"),
    ("fish_farmers", "Fish Farmers / Aquaculture Group"),
    ("environment", "Environmental / Conservation Group"),
    ("faith", "Faith-Based Community Group"),
    ("farmers", "Farmers / Producer Group"),
    ("pwd", "PWD / Special Interest Group"),
    ("chama", "Investment Chama (non-SACCO)"),
    ("other", "Other (describe in follow-up)"),
)
