# Generated by Django 5.2.10 on 2026-05-09 21:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('group_type', models.CharField(choices=[('cbo', 'Community Based Organization'), ('youth', 'Youth Forum / Group'), ('women', 'Women Group'), ('sacco', 'SACCO / Financial Collective'), ('environment', 'Environmental Group'), ('fish_farmers', 'Fish Farmers'), ('stakeholder', 'Stakeholder Cell'), ('other', 'Other')], max_length=40)),
                ('motto', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, upload_to='group_logos/')),
                ('registration_number', models.CharField(blank=True, max_length=120)),
                ('registration_authority', models.CharField(blank=True, max_length=160)),
                ('founded_on', models.DateField(blank=True, null=True)),
                ('county', models.CharField(default='Kiambu', max_length=120)),
                ('ward', models.CharField(blank=True, max_length=120)),
                ('location_notes', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('summary', models.TextField(blank=True)),
                ('narrative', models.TextField(blank=True)),
                ('chairs_message', models.TextField(blank=True)),
                ('secretary_name', models.CharField(blank=True, max_length=160)),
                ('treasurer_name', models.CharField(blank=True, max_length=160)),
                ('members_count_cached', models.PositiveIntegerField(default=0)),
                ('partner_organizations', models.TextField(blank=True)),
                ('thematic_focus_tags', models.CharField(blank=True, max_length=255)),
                ('annual_budget_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_groups', to=settings.AUTH_USER_MODEL)),
                ('leaders', models.ManyToManyField(blank=True, help_text='Designated coordinators with elevated group permissions.', related_name='led_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('core_member', 'Core Member'), ('patron', 'Patron'), ('volunteer', 'Volunteer'), ('beneficiary_rep', 'Beneficiary Representative')], default='core_member', max_length=48)),
                ('verified', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.communitygroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'group')},
            },
        ),
    ]
