# Generated by Django 5.2.10 on 2026-05-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupJoinApplication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_number', models.CharField(help_text='Official registration or certificate number — must be unique.', max_length=120, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('chairperson_name', models.CharField(help_text='Chairperson or primary contact person', max_length=160)),
                ('group_type', models.CharField(choices=[('cbo', 'Community Based Organisation (CBO)'), ('self_help', 'Self-Help Group'), ('savings', 'Savings Group / Table Banking'), ('women', 'Women Group / Women Enterprise'), ('youth', 'Youth Group / Youth Forum'), ('sacco', 'SACCO / Financial Cooperative'), ('fish_farmers', 'Fish Farmers / Aquaculture Group'), ('environment', 'Environmental / Conservation Group'), ('faith', 'Faith-Based Community Group'), ('farmers', 'Farmers / Producer Group'), ('pwd', 'PWD / Special Interest Group'), ('chama', 'Investment Chama (non-SACCO)'), ('other', 'Other (describe in follow-up)')], max_length=64)),
                ('ward', models.CharField(choices=[('gituamba', 'Gituamba — Gatundu North'), ('githobokoni', 'Githobokoni — Gatundu North'), ('chania', 'Chania — Gatundu North'), ('mangu', "Mang'u — Gatundu North"), ('kiamwangi', 'Kiamwangi — Gatundu South'), ('kiganjo', 'Kiganjo — Gatundu South'), ('ndarugo', 'Ndarugo — Gatundu South'), ('ngenda', 'Ngenda — Gatundu South'), ('murera', 'Murera — Juja'), ('theta', 'Theta — Juja'), ('witeithie', 'Witeithie — Juja'), ('kalimoni', 'Kalimoni — Juja'), ('juja', 'Juja — Juja'), ('thika_township', 'Township — Thika Town'), ('kamenu', 'Kamenu — Thika Town'), ('hospital', 'Hospital — Thika Town'), ('gatuanyaga', 'Gatuanyaga — Thika Town'), ('ngoliba', 'Ngoliba — Thika Town'), ('gitothua', 'Gitothua — Ruiru'), ('biashara', 'Biashara — Ruiru'), ('gatongora', 'Gatongora — Ruiru'), ('kahawa_sukari', 'Kahawa Sukari — Ruiru'), ('kahawa_wendani', 'Kahawa Wendani — Ruiru'), ('kiuu', 'Kiuu — Ruiru'), ('mwiki', 'Mwiki — Ruiru'), ('mwihoko', 'Mwihoko — Ruiru'), ('githunguri', 'Githunguri — Githunguri'), ('githiga', 'Githiga — Githunguri'), ('ikinu', 'Ikinu — Githunguri'), ('ngewa', 'Ngewa — Githunguri'), ('komothai', 'Komothai — Githunguri'), ('tinganga', "Ting'ang'a — Kiambu"), ('ndumberi', 'Ndumberi — Kiambu'), ('riabai', 'Riabai — Kiambu'), ('kiambu_township', 'Township — Kiambu'), ('cianda', 'Cianda — Kiambaa'), ('karuri', 'Karuri — Kiambaa'), ('ndenderu', 'Ndenderu — Kiambaa'), ('muchatha', 'Muchatha — Kiambaa'), ('kihara', 'Kihara — Kiambaa'), ('gitaru', 'Gitaru — Kabete'), ('muguga', 'Muguga — Kabete'), ('nyadhuna', 'Nyadhuna — Kabete'), ('kabete', 'Kabete — Kabete'), ('uthiru', 'Uthiru — Kabete'), ('karai', 'Karai — Kikuyu'), ('nachu', 'Nachu — Kikuyu'), ('sigona', 'Sigona — Kikuyu'), ('kikuyu', 'Kikuyu — Kikuyu'), ('kinoo', 'Kinoo — Kikuyu'), ('bibirioni', 'Bibirioni — Limuru'), ('limuru_central', 'Limuru Central — Limuru'), ('ndeiya', 'Ndeiya — Limuru'), ('limuru_east', 'Limuru East — Limuru'), ('ngecha_tigoni', 'Ngecha Tigoni — Limuru'), ('kinale', 'Kinale — Lari'), ('kijabe', 'Kijabe — Lari'), ('nyanduma', 'Nyanduma — Lari'), ('kamburu', 'Kamburu — Lari'), ('lari_kirenga', 'Lari / Kirenga — Lari')], max_length=64)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('under_review', 'Under review'), ('approved', 'Approved'), ('rejected', 'Not admitted'), ('duplicate', 'Closed — duplicate')], db_index=True, default='pending', max_length=32)),
                ('email_to_team_sent_at', models.DateTimeField(blank=True, null=True)),
                ('secretariat_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Group join application',
                'verbose_name_plural': 'Group join applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
